### ISSUE TITLE
Plan by Changha

### ISSUE THREAD

**Issue by LEEJB-1217** [NYCCake/SmartOMR#2]

**Comment by chang-ha** [comment]
![pro](https://user-images.githubusercontent.com/76558979/104551804-e7ce7c00-567a-11eb-8e4e-fc92dd097d98.PNG)

현재 vscode에서 코드를 디버깅 해보고있는데 
module compiled against API version 0xb but this version of numpy is 0xa
라는 에러가 발생, 제가 찾아본 결과는 numpy버전이 최신이 아닐때 나오는 에러라고 함. 하지만 numpy는 현재 최신버전이고 해당 에러가 떳다 안떳다하면서 작업시간이 현저히 내려감. 어제부터 계속 가상환경을 새로 만들거나 프로그램을 재설치, numpy재설치 등 여러 해결법을 시도해봤지만 계속 같은 에러발생. 기술적인 문제는 되도록 혼자 해결해보려헀지만 작은 도움을 구하고자 이슈를 남김. 

@LEEJB-1217 @EstEsca @estesca11

**Comment by EstEsca** [comment]
imutils 버전을 업그레이드 해보시겠어요? >pip upgrade imutils @chang-ha

**Comment by chang-ha** [comment]
모든 라이브러리랑 아나콘다 파이썬 전부 업그레이드 해봤습니다 @EstEsca

**Comment by EstEsca** [comment]
@chang-ha 아나콘다에서 어떤 버전 쓰고 있는지 캡처해주고, 

https://code.visualstudio.com/docs/python/environments 여기에서 말하는대로, vscode에서 파이썬 가상환경이 잘 선택됐는지 확인해줄래? 가상환경이 잘 구축돼도 vscode에서 다른 환경을 쓰고 있을지도 모르니까

https://github.com/formulahendry/vscode-code-runner/issues/222

**Comment by chang-ha** [comment]
![확인](https://user-images.githubusercontent.com/76558979/104556289-a772fc00-5682-11eb-9858-746bcb3ebbc1.PNG)
![version](https://user-images.githubusercontent.com/76558979/104556292-a8a42900-5682-11eb-8d17-ac618eee5b4f.PNG)

가상환경 test:conda되어있고, 버전은 terminal에 나와있습니다.
@EstEsca

**Comment by EstEsca** [comment]
아나콘다 GUI 환경에서 설치한 패키지(Numpy)를 CUI 환경에서 업그레이드 하는 과정에서, 새로 업그레이드된 버전을 (가상 환경이) 제대로 인식하지 못한 것 같습니다. 이슈 닫습니다~
