### ISSUE TITLE
회의 Issue

### ISSUE THREAD

**Issue by LEEJB-1217** [NYCCake/SmartOMR#6]
회의에서 다룰 Issue들을 Comment에 작성해주세요.
작성된 Comment들은 회의에서 다뤄질 예정입니다.

**Comment by estesca11** [comment]
vscode에서 opencv-python에 대한 intellisense가 잘 작동하지 않는 문제

**Comment by chang-ha** [comment]
git허브 사용법
@LEEJB-1217

**Comment by LEEJB-1217** [comment]
@chang-ha HIHI
